# -*- coding: utf-8 -*-
"""
Created on Fri Jun 18 18:29:00 2021

@author: fhu14

There seems to be a difference in values between mio and skf, where using the 
aurog parameter dictionary with the mio skfs gives differing results between
DFTBpy and DFTB+. Why is there a discrepancy when the mio parameter set 
and the auorg parameter set should be the same? 

One way to investigate this is to look at the H, G, R, and S matrices
generated by DFTBpy across these different parameter sets.
"""
#%% Imports, definitions
from mio_0_1 import ParDict
mio_pardict = ParDict()
from auorg_1_1 import ParDict
auorg_pardict = ParDict()
from dftb import DFTB
import numpy as np
from run_dftbplus import load_ani1, add_dftb
import os

#%% Load in test molecule
"""
To keep things simple, going to use C1H1N1, 0th configuration.
"""
data_path = os.path.join(os.getcwd(), "data", "ANI-1ccx_clean_fullentry.h5")
max_config = 1
dataset = load_ani1(data_path, max_config)
test_molec = dataset[0]
assert(test_molec['name'] == 'C1H1N1' and test_molec['iconfig'] == 0)

# test_molec = {'name': 'C1H1N1', 
#  'iconfig': 0, 
#  'atomic_numbers':np.array([6, 1, 7]), 
#  'coordinates': np.array([[ 1.4473461e-02,  4.9763787e-01, -5.8813488e-17],
#        [-1.8815500e-01,  1.6787970e+00, -1.9515246e-16],
#        [ 1.4473461e-02, -6.6637492e-01,  7.4421870e-17]]), 
#  'targets': {'dt': -4.430810242688221, 
#              'dr': 0.25864039431560015, 
#              'pt': -4.4324082414, 
#              'pe': -4.691048449, 
#              'pr': 0.2586402076, 
#              'cc': -93.31514939321461, 
#              'ht': -92.89307544370118, 
#              'dipole': np.array([-5.3488452e-02,  6.4492357e-01, -6.8211226e-17]), 
#              'charges': np.array([ 0.12561 ,  0.201823, -0.327431])}
#  }

#%% Initialize DFTB objects

Zs = test_molec['atomic_numbers']
rcart = test_molec['coordinates']

# Input format for python dftb.py
natom = len(Zs)
cart = np.zeros([natom,4])
cart[:,0] = Zs
for ix in range(3):
    cart[:,ix+1] = rcart[:,ix]
charge = 0
mult = 1

dftb_auorg = DFTB(auorg_pardict, cart, charge, mult)
dftb_mio = DFTB(mio_pardict, cart, charge, mult)

auorg_coreH = dftb_auorg.GetCoreH()
mio_coreH = dftb_mio.GetCoreH()


#%% Analyze H, G, S, R operators



#%% Main block

if __name__ == "__main__":
    pass

