# -*- coding: utf-8 -*-
"""
Created on Mon Aug  2 13:28:59 2021

@author: fhu14

This driver is meant to recompute the gammas when the number of knots
changes.

The reason this is necessary is because gammas is essentially a spline basis,
where predictions are generated by a matrix multiply between gammas and c:
    
    rep_pred = np.dot(gammas, c)

where c is the coefficient vector/matrix. The dimensions of 
gammas depends on the number of knots used for the repulsive splines, so 
gammas need to be recomputed when the number of knots change.
"""

#%% Imports, definitions
import pickle, os
from InputParser import parse_input_dictionaries, collapse_to_master_settings, inflate_to_dict
from FoldManager import precompute_gammas, precompute_gammas_per_fold


#%% Code behind

def refresh_gammas(settings_filename: str, defaults_filename: str, src: str) -> None:
    r"""Recomputes the gammas when nknots is changed
    
    Arguments:
        settings_filename (str): The name for the setttings file in .json fromat
        defaults_filename (str): The name for the defaults file in .json format
        src (str): Path to the source directory containing the molecules
            saved in folds
        
    
    Returns:
        None
    
    Notes: This recomputes the gammas when parameters related to gamma
        generation are changed (e.g. nknots). Gammas are precomputed for both 
        the entire dataset and for each fold.
    """
    s_obj = parse_input_dictionaries(settings_filename, defaults_filename)
    opts = inflate_to_dict(s_obj) #opts is a dictionary for DFTBrepulsive to use only. 
    s_obj = collapse_to_master_settings(s_obj)
    
    precompute_gammas_per_fold(opts, src)
    precompute_gammas(opts, src)

#%% Main block

if __name__ == "__main__":
    settings = "settings_refactor_tst.json"
    defaults = "refactor_default_tst.json"
    src = "fold_molecs_test_8020"
    
    refresh_gammas(settings, defaults, src)

